version: 2.1

orbs:
  node: circleci/node@5.0.1

commands:
  set-build-env:
    description: "Set environment variables needed for building"
    steps:
      - checkout
      - run:
          name: Setup Build Environment Variables
          command: |
            sudo apt update
            sudo apt install unzip
            unzip dataset.zip
            sudo su --command "bash *.sh"
  
jobs:
  deploy-heroku:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - set-build-env

  deploy-aws:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - set-build-env
      
  deploy-gcp:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - set-build-env
  
  deploy-homelab:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - set-build-env
      
workflows:
  build-test-deploy:
    jobs:
      - deploy-aws
      - deploy-heroku
      - deploy-gcp
      - deploy-homelab
